import { eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { appUsers, captainProfiles, leagueAdminProfiles, leagueSeasons, leagueTeams, matches, players, seasons } from "../../../../db/schema";
import { requireUser } from "../../auth/security";

type Stat={name:string;played:number;wins:number;losses:number;score:number};

export async function GET(request:Request){
  const auth=await requireUser(request);if(auth.response)return auth.response;if(auth.user.role!=="LeagueAdmin")return Response.json({error:"League administrator access required"},{status:403});
  const db=getDb(),[profile]=await db.select().from(leagueAdminProfiles).where(eq(leagueAdminProfiles.userId,auth.user.id));if(!profile)return Response.json({error:"League profile not found"},{status:403});
  const [leagueTeamRows,captainRows,userRows,leagueSeasonRows,localMatches,localPlayers,localSeasons]=await Promise.all([db.select().from(leagueTeams).where(eq(leagueTeams.organizationId,profile.organizationId)),db.select().from(captainProfiles).where(eq(captainProfiles.organizationId,profile.organizationId)),db.select().from(appUsers),db.select().from(leagueSeasons).where(eq(leagueSeasons.organizationId,profile.organizationId)),db.select().from(matches),db.select().from(players),db.select().from(seasons)]);
  const reports=leagueTeamRows.map(team=>{const captain=captainRows.find(item=>item.leagueTeamId===team.id),user=userRows.find(item=>item.id===captain?.userId),leagueSeason=leagueSeasonRows.find(item=>item.id===team.seasonId),localSeasonIds=new Set(localSeasons.filter(item=>item.teamId===user?.teamId&&item.name===leagueSeason?.name).map(item=>item.id)),teamMatches=localMatches.filter(item=>item.teamId===user?.teamId&&localSeasonIds.has(item.seasonId)),pairMap=new Map<string,Stat>(),playerMap=new Map<string,Stat>();for(const match of teamMatches){const lineup=match.lineup?JSON.parse(match.lineup) as {round:number;courts:string[][]}[]:[],results=match.results?JSON.parse(match.results) as Record<string,"W"|"L">:{};for(const round of lineup)round.courts.forEach((pair,index)=>{const result=results[`${round.round}-${index+1}`];if(!result)return;const sorted=[...pair].sort(),pairName=sorted.join(" + ");const pairStat=pairMap.get(pairName)??{name:pairName,played:0,wins:0,losses:0,score:0};pairStat.played++;result==="W"?pairStat.wins++:pairStat.losses++;pairMap.set(pairName,pairStat);for(const name of pair){const playerStat=playerMap.get(name)??{name,played:0,wins:0,losses:0,score:0};playerStat.played++;result==="W"?playerStat.wins++:playerStat.losses++;playerMap.set(name,playerStat)}})}const finish=(values:Stat[])=>values.map(item=>({...item,rate:item.played?Math.round(item.wins/item.played*100):0,score:item.played?Math.round(50+((item.wins/item.played)-.5)*(item.played/(item.played+4))*100):50})).sort((a,b)=>b.score-a.score||b.played-a.played);return {teamId:team.id,teamName:`${team.city} · ${team.teamName}`,seasonId:team.seasonId,seasonName:leagueSeason?.name??"Season",rosterCount:localPlayers.filter(item=>item.teamId===user?.teamId).length,pairs:finish([...pairMap.values()]),players:finish([...playerMap.values()])}});
  return Response.json({seasons:leagueSeasonRows,reports});
}
