import { and, eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { captainProfiles, leagueLevels, leagueMatches, leagueSeasons, leagueTeams, leagueVenues, matches, opponents, seasons, teamSettings, venues } from "../../../../db/schema";
import { ensureInterclubAuthSchema } from "../../auth/interclub-schema";
import { requireUser } from "../../auth/security";

const parsed=(row:typeof matches.$inferSelect)=>({...row,playerIds:JSON.parse(row.playerIds),lineup:row.lineup?JSON.parse(row.lineup):null,results:row.results?JSON.parse(row.results):{}});

export async function POST(request:Request){try{
  const auth=await requireUser(request);if(auth.response)return auth.response;if(auth.user!.role!=="Captain")return Response.json({error:"Captain access required"},{status:403});
  await ensureInterclubAuthSchema();const input=await request.json() as {leagueMatchId?:number};const db=getDb(),[profile]=await db.select().from(captainProfiles).where(eq(captainProfiles.userId,auth.user!.id));if(!profile)return Response.json({error:"Interclub captain profile not found"},{status:404});
  const[leagueMatch]=await db.select().from(leagueMatches).where(and(eq(leagueMatches.id,Number(input.leagueMatchId)),eq(leagueMatches.organizationId,profile.organizationId)));if(!leagueMatch||leagueMatch.homeTeamId!==profile.leagueTeamId&&leagueMatch.visitorTeamId!==profile.leagueTeamId)return Response.json({error:"Assigned match not found"},{status:404});
  const[ownTeam]=await db.select().from(leagueTeams).where(eq(leagueTeams.id,profile.leagueTeamId)),opponentTeamId=leagueMatch.homeTeamId===profile.leagueTeamId?leagueMatch.visitorTeamId:leagueMatch.homeTeamId,[opponentTeam]=await db.select().from(leagueTeams).where(eq(leagueTeams.id,opponentTeamId)),[leagueSeason]=await db.select().from(leagueSeasons).where(eq(leagueSeasons.id,leagueMatch.seasonId)),[division]=await db.select().from(leagueLevels).where(eq(leagueLevels.id,leagueMatch.levelId)),[leagueVenue]=await db.select().from(leagueVenues).where(eq(leagueVenues.id,leagueMatch.venueId));
  if(!ownTeam||!opponentTeam||!leagueSeason||!leagueVenue)return Response.json({error:"The league match configuration is incomplete"},{status:400});
  const localSeasons=await db.select().from(seasons).where(eq(seasons.teamId,auth.user!.teamId));let localSeason=localSeasons.find(item=>item.name===leagueSeason.name);if(!localSeason){await Promise.all(localSeasons.filter(item=>item.status==="Active").map(item=>db.update(seasons).set({status:"Closed",closedAt:new Date().toISOString()}).where(eq(seasons.id,item.id))));[localSeason]=await db.insert(seasons).values({teamId:auth.user!.teamId,name:leagueSeason.name,status:"Active"}).returning()}else if(localSeason.status!=="Active"){await Promise.all(localSeasons.filter(item=>item.status==="Active").map(item=>db.update(seasons).set({status:"Closed",closedAt:new Date().toISOString()}).where(eq(seasons.id,item.id))));[localSeason]=await db.update(seasons).set({status:"Active",closedAt:null}).where(eq(seasons.id,localSeason.id)).returning()}
  await db.update(teamSettings).set({teamName:`${ownTeam.city} · ${ownTeam.teamName}`,captainName:profile.displayName,category:division?.name==="Development"?"Development":"Performance"}).where(eq(teamSettings.id,auth.user!.teamId));
  const localVenues=await db.select().from(venues).where(eq(venues.teamId,auth.user!.teamId));if(!localVenues.some(item=>item.name===leagueVenue.name))await db.insert(venues).values({teamId:auth.user!.teamId,name:leagueVenue.name,status:"Active"});
  const localOpponents=await db.select().from(opponents).where(eq(opponents.teamId,auth.user!.teamId));if(!localOpponents.some(item=>item.city===opponentTeam.city&&item.teamName===opponentTeam.teamName))await db.insert(opponents).values({teamId:auth.user!.teamId,city:opponentTeam.city,teamName:opponentTeam.teamName,defaultStrength:"Equal",status:"Active"});
  const opponentLabel=`${opponentTeam.city} · ${opponentTeam.teamName}`,existing=await db.select().from(matches).where(and(eq(matches.teamId,auth.user!.teamId),eq(matches.seasonId,localSeason.id),eq(matches.matchDate,leagueMatch.matchDate),eq(matches.opponent,opponentLabel)));let localMatch=existing[0];
  if(!localMatch){[localMatch]=await db.insert(matches).values({teamId:auth.user!.teamId,seasonId:localSeason.id,opponent:opponentLabel,matchDate:leagueMatch.matchDate,matchTime:leagueMatch.matchTime,location:leagueVenue.name,opponentStrength:"Equal",homeAway:leagueMatch.homeTeamId===profile.leagueTeamId?"Local":"Visitor",court1:JSON.parse(leagueMatch.courts)[0]??"1",court2:JSON.parse(leagueMatch.courts)[1]??"2",court3:JSON.parse(leagueMatch.courts)[2]??"3",playerIds:"[]",status:"Upcoming"}).returning()}
  return Response.json({match:parsed(localMatch),season:localSeason,settings:{teamName:`${ownTeam.city} · ${ownTeam.teamName}`,captainName:profile.displayName,category:division?.name==="Development"?"Development":"Performance"}});
}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to prepare the assigned match"},{status:500})}}
