"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Answer="Available"|"Unavailable"|"Maybe";
type Poll={pollStatus:"Open"|"Closed";teamName:string;opponent:string;matchDate:string;matchTime:string;location:string;players:{id:number;name:string}[];responses:{playerId:number;response:Answer;note:string}[]};
type Locale="fr"|"en";
const copy={
  fr:{title:"Confirmer votre disponibilité",loading:"Chargement…",missing:"Cette invitation n’existe pas ou n’est plus disponible.",who:"Votre nom",choose:"Sélectionnez votre nom",question:"Êtes-vous disponible?",available:"Disponible",unavailable:"Pas disponible",maybe:"Peut-être",note:"Note facultative",placeholder:"Ajoutez un détail si nécessaire",save:"Confirmer ma réponse",saving:"Enregistrement…",confirm:"Vous répondez pour",saved:"Merci! Votre réponse a été enregistrée.",change:"Vous pouvez revenir sur ce lien pour modifier votre réponse.",closed:"Cette invitation est fermée."},
  en:{title:"Confirm your availability",loading:"Loading…",missing:"This invitation does not exist or is no longer available.",who:"Your name",choose:"Select your name",question:"Are you available?",available:"Available",unavailable:"Not available",maybe:"Maybe",note:"Optional note",placeholder:"Add a detail if needed",save:"Confirm my response",saving:"Saving…",confirm:"You are responding for",saved:"Thank you! Your response was saved.",change:"You can return to this link to change your response.",closed:"This invitation is closed."},
} as const;

export default function AvailabilityPage(){
  const [locale,setLocale]=useState<Locale>("fr"),[poll,setPoll]=useState<Poll|null>(null),[missing,setMissing]=useState(false);
  const [playerId,setPlayerId]=useState<number|"">(""),[answer,setAnswer]=useState<Answer|"">(""),[note,setNote]=useState(""),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
  const text=copy[locale],token=typeof window==="undefined"?"":window.location.pathname.split("/").filter(Boolean).at(-1)??"";
  const selected=useMemo(()=>poll?.players.find(player=>player.id===playerId),[poll,playerId]);
  useEffect(()=>{if(!token)return;fetch(`/api/availability/${encodeURIComponent(token)}`).then(async response=>{if(!response.ok)throw new Error();setPoll(await response.json() as Poll)}).catch(()=>setMissing(true))},[token]);
  useEffect(()=>{if(!poll||!playerId)return;const previous=poll.responses.find(item=>item.playerId===playerId);setAnswer(previous?.response??"");setNote(previous?.note??"");setSaved(false)},[poll,playerId]);
  async function submit(event:FormEvent){event.preventDefault();if(!selected||!answer)return;if(!window.confirm(`${text.confirm} ${selected.name}. ${locale==="fr"?"Confirmer?":"Confirm?"}`))return;setSaving(true);const response=await fetch(`/api/availability/${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({playerId,response:answer,note})});setSaving(false);if(!response.ok){setMissing(true);return}setPoll(current=>current?{...current,responses:[...current.responses.filter(item=>item.playerId!==playerId),{playerId,response:answer,note}]}:current);setSaved(true)}
  const language=<div className="public-language"><button className={locale==="fr"?"active":""} onClick={()=>setLocale("fr")}>FR</button><button className={locale==="en"?"active":""} onClick={()=>setLocale("en")}>EN</button></div>;
  if(missing)return <main className="availability-public"><section className="availability-card">{language}<p className="public-brand"><img src="/brand/picklepilot-mark.svg" alt=""/>PICKLEPILOT</p><h1>{text.missing}</h1></section></main>;
  if(!poll)return <main className="availability-public"><section className="availability-card">{language}<p>{text.loading}</p></section></main>;
  return <main className="availability-public"><section className="availability-card">{language}<p className="public-brand"><img src="/brand/picklepilot-mark.svg" alt=""/>PICKLEPILOT</p><p className="eyebrow">{poll.teamName}</p><h1>{text.title}</h1><div className="availability-match"><strong>{poll.teamName} vs {poll.opponent}</strong><span>{new Date(`${poll.matchDate}T12:00:00`).toLocaleDateString(locale==="fr"?"fr-CA":"en-CA",{weekday:"long",day:"numeric",month:"long"})} · {poll.matchTime}</span><span>{poll.location}</span></div>{poll.pollStatus==="Closed"?<div className="availability-closed">{text.closed}</div>:<form onSubmit={submit}><label>{text.who}<select required value={playerId} onChange={event=>setPlayerId(Number(event.target.value)||"")}><option value="">{text.choose}</option>{poll.players.map(player=><option key={player.id} value={player.id}>{player.name}</option>)}</select></label><fieldset><legend>{text.question}</legend><div className="availability-options"><button type="button" className={answer==="Available"?"selected available":""} onClick={()=>setAnswer("Available")}>✓ {text.available}</button><button type="button" className={answer==="Unavailable"?"selected unavailable":""} onClick={()=>setAnswer("Unavailable")}>× {text.unavailable}</button><button type="button" className={answer==="Maybe"?"selected maybe":""} onClick={()=>setAnswer("Maybe")}>? {text.maybe}</button></div></fieldset><label>{text.note}<textarea maxLength={180} value={note} onChange={event=>setNote(event.target.value)} placeholder={text.placeholder}/></label>{saved&&<div className="availability-success"><strong>{text.saved}</strong><span>{text.change}</span></div>}<button className="primary-btn availability-submit" disabled={!playerId||!answer||saving}>{saving?text.saving:text.save}</button></form>}</section></main>;
}
