import { and, eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { appUsers, captainProfiles, leagueAdminProfiles, leagueLevels, leagueSeasons, leagueTeams, teamSettings } from "../../../../db/schema";
import { ensureInterclubAuthSchema } from "../../auth/interclub-schema";
import { hashPassword, randomHex, requireUser } from "../../auth/security";

async function context(request:Request){const auth=await requireUser(request);if(auth.response)return {response:auth.response,organizationId:0};if(auth.user!.role!=="LeagueAdmin")return {response:Response.json({error:"League administrator access required"},{status:403}),organizationId:0};await ensureInterclubAuthSchema();const [profile]=await getDb().select().from(leagueAdminProfiles).where(eq(leagueAdminProfiles.userId,auth.user!.id));return profile?{response:null,organizationId:profile.organizationId}:{response:Response.json({error:"Organization not found"},{status:404}),organizationId:0}}
const temporaryPassword=()=>`Pilot-${randomHex(4)}`;

export async function GET(request:Request){const ctx=await context(request);if(ctx.response)return ctx.response;const db=getDb();const teams=await db.select().from(leagueTeams).where(eq(leagueTeams.organizationId,ctx.organizationId));const captains=await db.select({userId:captainProfiles.userId,leagueTeamId:captainProfiles.leagueTeamId,displayName:captainProfiles.displayName,email:captainProfiles.email,phone:captainProfiles.phone,mustChangePassword:captainProfiles.mustChangePassword,username:appUsers.username}).from(captainProfiles).innerJoin(appUsers,eq(captainProfiles.userId,appUsers.id)).where(eq(captainProfiles.organizationId,ctx.organizationId));return Response.json({teams,captains})}

export async function POST(request:Request){try{const ctx=await context(request);if(ctx.response)return ctx.response;const input=await request.json() as {seasonId?:number;levelId?:number;city?:string;teamName?:string;captainName?:string;username?:string;email?:string;phone?:string};const city=input.city?.trim(),teamName=input.teamName?.trim(),captainName=input.captainName?.trim(),username=input.username?.trim().toLowerCase(),email=input.email?.trim().toLowerCase();if(!input.seasonId||!input.levelId||!city||!teamName||!captainName||!username||!email?.includes("@"))return Response.json({error:"Complete all required team and captain fields"},{status:400});const db=getDb();const [season]=await db.select().from(leagueSeasons).where(and(eq(leagueSeasons.id,input.seasonId),eq(leagueSeasons.organizationId,ctx.organizationId)));const [level]=await db.select().from(leagueLevels).where(and(eq(leagueLevels.id,input.levelId),eq(leagueLevels.seasonId,input.seasonId)));if(!season||!level)return Response.json({error:"Invalid season or level"},{status:400});const [existing]=await db.select().from(appUsers).where(eq(appUsers.username,username));if(existing)return Response.json({error:"This username is already in use"},{status:409});const password=temporaryPassword(),salt=randomHex(16),passwordHash=await hashPassword(password,salt);const [settings]=await db.insert(teamSettings).values({teamName:`${city} · ${teamName}`,captainName,category:level.name==="Development"?"Development":"Performance"}).returning();const [user]=await db.insert(appUsers).values({username,passwordHash,passwordSalt:salt,role:"Captain",teamId:settings.id}).returning();const [team]=await db.insert(leagueTeams).values({organizationId:ctx.organizationId,seasonId:input.seasonId,levelId:input.levelId,city,teamName,captainUserId:user.id}).returning();await db.insert(captainProfiles).values({userId:user.id,organizationId:ctx.organizationId,leagueTeamId:team.id,displayName:captainName,email,phone:input.phone?.trim()||null,mustChangePassword:true});return Response.json({team,temporaryPassword:password,username},{status:201})}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to create team"},{status:500})}}

export async function PUT(request:Request){try{const ctx=await context(request);if(ctx.response)return ctx.response;const input=await request.json() as {id?:number;levelId?:number;city?:string;teamName?:string;captainName?:string;username?:string;email?:string;phone?:string};const db=getDb();const [team]=await db.select().from(leagueTeams).where(and(eq(leagueTeams.id,Number(input.id)),eq(leagueTeams.organizationId,ctx.organizationId)));if(!team||!team.captainUserId)return Response.json({error:"Team not found"},{status:404});const city=input.city?.trim(),teamName=input.teamName?.trim(),captainName=input.captainName?.trim(),username=input.username?.trim().toLowerCase(),email=input.email?.trim().toLowerCase();if(!input.levelId||!city||!teamName||!captainName||!username||!email?.includes("@"))return Response.json({error:"Complete all required fields"},{status:400});const [level]=await db.select().from(leagueLevels).where(and(eq(leagueLevels.id,input.levelId),eq(leagueLevels.seasonId,team.seasonId)));if(!level)return Response.json({error:"Invalid level"},{status:400});const [duplicate]=await db.select().from(appUsers).where(eq(appUsers.username,username));if(duplicate&&duplicate.id!==team.captainUserId)return Response.json({error:"This username is already in use"},{status:409});const [user]=await db.select().from(appUsers).where(eq(appUsers.id,team.captainUserId));await db.update(leagueTeams).set({levelId:input.levelId,city,teamName}).where(eq(leagueTeams.id,team.id));await db.update(captainProfiles).set({displayName:captainName,email,phone:input.phone?.trim()||null}).where(eq(captainProfiles.userId,team.captainUserId));await db.update(appUsers).set({username}).where(eq(appUsers.id,team.captainUserId));if(user)await db.update(teamSettings).set({teamName:`${city} · ${teamName}`,captainName,category:level.name==="Development"?"Development":"Performance"}).where(eq(teamSettings.id,user.teamId));return Response.json({ok:true})}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to update team"},{status:500})}}

export async function PATCH(request:Request){try{const ctx=await context(request);if(ctx.response)return ctx.response;const input=await request.json() as {id?:number};const db=getDb();const [team]=await db.select().from(leagueTeams).where(and(eq(leagueTeams.id,Number(input.id)),eq(leagueTeams.organizationId,ctx.organizationId)));if(!team?.captainUserId)return Response.json({error:"Team not found"},{status:404});const password=temporaryPassword(),salt=randomHex(16),passwordHash=await hashPassword(password,salt);await db.update(appUsers).set({passwordHash,passwordSalt:salt}).where(eq(appUsers.id,team.captainUserId));await db.update(captainProfiles).set({mustChangePassword:true}).where(eq(captainProfiles.userId,team.captainUserId));const [user]=await db.select().from(appUsers).where(eq(appUsers.id,team.captainUserId));return Response.json({username:user.username,temporaryPassword:password})}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to reset password"},{status:500})}}

export async function DELETE(request:Request){const ctx=await context(request);if(ctx.response)return ctx.response;const id=Number(new URL(request.url).searchParams.get("id"));const db=getDb();const [team]=await db.select().from(leagueTeams).where(and(eq(leagueTeams.id,id),eq(leagueTeams.organizationId,ctx.organizationId)));if(!team)return Response.json({error:"Team not found"},{status:404});if(team.captainUserId){const [user]=await db.select().from(appUsers).where(eq(appUsers.id,team.captainUserId));await db.delete(captainProfiles).where(eq(captainProfiles.userId,team.captainUserId));await db.delete(appUsers).where(eq(appUsers.id,team.captainUserId));if(user)await db.delete(teamSettings).where(eq(teamSettings.id,user.teamId))}await db.delete(leagueTeams).where(eq(leagueTeams.id,id));return Response.json({ok:true})}
