import { and, eq, or } from "drizzle-orm";
import { getDb } from "../../../../db";
import { captainProfiles, leagueAdminProfiles, leagueLevels, leagueMatches, leagueSeasons, leagueTeams, leagueVenues } from "../../../../db/schema";
import { ensureInterclubAuthSchema } from "../../auth/interclub-schema";
import { requireUser } from "../../auth/security";

async function context(request:Request){
  const auth=await requireUser(request);if(auth.response)return{response:auth.response,organizationId:0,role:"",teamId:0};
  await ensureInterclubAuthSchema();const user=auth.user!;
  if(user.role==="LeagueAdmin"){const[profile]=await getDb().select().from(leagueAdminProfiles).where(eq(leagueAdminProfiles.userId,user.id));return profile?{response:null,organizationId:profile.organizationId,role:user.role,teamId:0}:{response:Response.json({error:"Organization not found"},{status:404}),organizationId:0,role:"",teamId:0}}
  if(user.role==="Captain"){const[profile]=await getDb().select().from(captainProfiles).where(eq(captainProfiles.userId,user.id));return profile?{response:null,organizationId:profile.organizationId,role:user.role,teamId:profile.leagueTeamId}:{response:Response.json({error:"Captain team not found"},{status:404}),organizationId:0,role:"",teamId:0}}
  return{response:Response.json({error:"Interclub access required"},{status:403}),organizationId:0,role:"",teamId:0};
}
const parsed=(row:typeof leagueMatches.$inferSelect)=>({...row,courts:JSON.parse(row.courts) as string[]});
export async function GET(request:Request){const ctx=await context(request);if(ctx.response)return ctx.response;const db=getDb();const rows=ctx.role==="Captain"?await db.select().from(leagueMatches).where(and(eq(leagueMatches.organizationId,ctx.organizationId),or(eq(leagueMatches.homeTeamId,ctx.teamId),eq(leagueMatches.visitorTeamId,ctx.teamId)))):await db.select().from(leagueMatches).where(eq(leagueMatches.organizationId,ctx.organizationId));const teams=await db.select().from(leagueTeams).where(eq(leagueTeams.organizationId,ctx.organizationId)),venues=await db.select().from(leagueVenues).where(eq(leagueVenues.organizationId,ctx.organizationId)),levels=await db.select().from(leagueLevels).where(eq(leagueLevels.organizationId,ctx.organizationId)),seasons=await db.select().from(leagueSeasons).where(eq(leagueSeasons.organizationId,ctx.organizationId)),captainTeam=teams.find(team=>team.id===ctx.teamId),captainLevel=levels.find(level=>level.id===captainTeam?.levelId),captainSeason=seasons.find(season=>season.id===captainTeam?.seasonId);return Response.json({matches:rows.map(row=>({...parsed(row),homeTeamName:(()=>{const team=teams.find(item=>item.id===row.homeTeamId);return team?`${team.city} · ${team.teamName}`:"Home"})(),visitorTeamName:(()=>{const team=teams.find(item=>item.id===row.visitorTeamId);return team?`${team.city} · ${team.teamName}`:"Visitor"})(),venueName:venues.find(item=>item.id===row.venueId)?.name??"Location"})),teamId:ctx.teamId,captainContext:captainTeam?{teamId:captainTeam.id,teamName:`${captainTeam.city} · ${captainTeam.teamName}`,divisionName:captainLevel?.name??"Division",seasonName:captainSeason?.name??"Season"}:null})}
export async function POST(request:Request){const ctx=await context(request);if(ctx.response)return ctx.response;if(ctx.role!=="LeagueAdmin")return Response.json({error:"League administrator access required"},{status:403});const input=await request.json() as {seasonId:number;date:string;time?:string;venueId:number;games:{levelId:number;homeTeamId:number;visitorTeamId:number;courts:string[]}[]};if(!input.seasonId||!input.date||!input.venueId||!input.games?.length)return Response.json({error:"Complete the game night"},{status:400});const db=getDb(),existing=await db.select().from(leagueMatches).where(and(eq(leagueMatches.organizationId,ctx.organizationId),eq(leagueMatches.seasonId,input.seasonId),eq(leagueMatches.matchDate,input.date))),allTeams=await db.select().from(leagueTeams).where(eq(leagueTeams.organizationId,ctx.organizationId)),scheduledTeams=new Set(existing.flatMap(match=>[match.homeTeamId,match.visitorTeamId])),batchTeams=new Set<number>(),usedCourts=new Set<string>();const teamLabel=(id:number)=>{const team=allTeams.find(item=>item.id===id);return team?`${team.city} · ${team.teamName}`:"This team"};for(const game of input.games){if(game.homeTeamId===game.visitorTeamId||game.courts.length!==3)return Response.json({error:"Each match needs different teams and 3 courts"},{status:400});for(const teamId of [game.homeTeamId,game.visitorTeamId]){if(scheduledTeams.has(teamId))return Response.json({error:`${teamLabel(teamId)} already has a match on this date`},{status:409});if(batchTeams.has(teamId))return Response.json({error:`${teamLabel(teamId)} was selected more than once for this game night`},{status:409});batchTeams.add(teamId)}for(const court of game.courts){if(usedCourts.has(court))return Response.json({error:`Court ${court} is used twice`},{status:400});usedCourts.add(court)}}const created=[];for(const game of input.games){const[row]=await db.insert(leagueMatches).values({organizationId:ctx.organizationId,seasonId:input.seasonId,levelId:game.levelId,venueId:input.venueId,matchDate:input.date,matchTime:input.time||"20:00",homeTeamId:game.homeTeamId,visitorTeamId:game.visitorTeamId,courts:JSON.stringify(game.courts)}).returning();created.push(parsed(row))}return Response.json({matches:created},{status:201})}
export async function PUT(request:Request){const ctx=await context(request);if(ctx.response)return ctx.response;if(ctx.role!=="LeagueAdmin")return Response.json({error:"League administrator access required"},{status:403});const input=await request.json() as {id?:number;levelId?:number;venueId?:number;date?:string;time?:string;homeTeamId?:number;visitorTeamId?:number;courts?:string[];comment?:string};const db=getDb(),[row]=await db.select().from(leagueMatches).where(and(eq(leagueMatches.id,Number(input.id)),eq(leagueMatches.organizationId,ctx.organizationId)));if(!row)return Response.json({error:"Match not found"},{status:404});if(!input.levelId||!input.venueId||!input.date||!input.time||!input.homeTeamId||!input.visitorTeamId||input.homeTeamId===input.visitorTeamId||input.courts?.length!==3)return Response.json({error:"Complete all match fields"},{status:400});const conflicts=(await db.select().from(leagueMatches).where(and(eq(leagueMatches.organizationId,ctx.organizationId),eq(leagueMatches.seasonId,row.seasonId),eq(leagueMatches.matchDate,input.date)))).filter(match=>match.id!==row.id&&[match.homeTeamId,match.visitorTeamId].some(teamId=>teamId===input.homeTeamId||teamId===input.visitorTeamId));if(conflicts.length){const allTeams=await db.select().from(leagueTeams).where(eq(leagueTeams.organizationId,ctx.organizationId)),teamId=[input.homeTeamId,input.visitorTeamId].find(id=>conflicts.some(match=>match.homeTeamId===id||match.visitorTeamId===id)),team=allTeams.find(item=>item.id===teamId);return Response.json({error:`${team?`${team.city} · ${team.teamName}`:"This team"} already has a match on this date`},{status:409})}const dateChanged=input.date!==row.matchDate;if(dateChanged&&!input.comment?.trim())return Response.json({error:"Add a reason when changing the match date"},{status:400});await db.update(leagueMatches).set({levelId:input.levelId,venueId:input.venueId,matchDate:input.date,matchTime:input.time,homeTeamId:input.homeTeamId,visitorTeamId:input.visitorTeamId,courts:JSON.stringify(input.courts),rescheduleComment:dateChanged?input.comment!.trim():row.rescheduleComment,updatedAt:new Date().toISOString()}).where(eq(leagueMatches.id,row.id));return Response.json({ok:true})}
export async function PATCH(request:Request){const ctx=await context(request);if(ctx.response)return ctx.response;const input=await request.json() as {id?:number;outcome?:"Home"|"Visitor"|"Tie";winnerWins?:number};if(!input.id||!input.outcome||!["Home","Visitor","Tie"].includes(input.outcome))return Response.json({error:"Choose the winning team or a tie"},{status:400});const[row]=await getDb().select().from(leagueMatches).where(eq(leagueMatches.id,input.id));if(!row||row.organizationId!==ctx.organizationId)return Response.json({error:"Match not found"},{status:404});if(ctx.role==="Captain"&&row.homeTeamId!==ctx.teamId)return Response.json({error:"Only the home captain can submit this result"},{status:403});const winnerWins=input.outcome==="Tie"?12:Number(input.winnerWins);if(!Number.isInteger(winnerWins)||winnerWins<12||winnerWins>24||input.outcome!=="Tie"&&winnerWins<13)return Response.json({error:"Enter 13 to 24 wins for the winning team"},{status:400});const homeWins=input.outcome==="Tie"?12:input.outcome==="Home"?winnerWins:24-winnerWins,visitorWins=input.outcome==="Tie"?12:input.outcome==="Visitor"?winnerWins:24-winnerWins;await getDb().update(leagueMatches).set({resultOutcome:input.outcome,homeWins,visitorWins,status:"Completed",resultSubmittedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}).where(eq(leagueMatches.id,row.id));return Response.json({ok:true})}
